### PR TITLE
fix(converter): dates

### LINKED ISSUE #9: Date Object disappears after case-converter use
Hi,

I'm facing a problem where dates keys converted through case-converter seems to be emptied.
Here, `user` is an object returned from my ORM. That's why `attributes` level is removed after toJSON() call.
```
> user.attributes.created_at
2016-08-17T09:56:04.236Z
  __proto__:Date
> user.toJSON().created_at
2016-08-17T09:56:04.236Z
  __proto__:Date
> caseConverter.toSnakeCase(user.toJSON()).created_at
Object
  __proto__:Object
```
toCamelCase have the same behavior (except the key is name createdAt, of course...).
Is this a bug or am I missing something ?

Thanks !

### PR DESCRIPTION
**Pull request by Moezalez**
Previously it tried to iterate over the enumerable properties of a date object, to convert their
keys. Since a date has no keys, it just returned an empty object. Now we filter out dates and do not
attempt to convert their keys. We do this by filtering everything out, that has no enumerable
properties.

closes #9

### CODE REVIEW

**Comment by Moezalez** [comment]
@Gpx Can you check this out? 
I did not find any bugs this would introduce, and tests keep passing. I'd still like to hear your opinion and see if there might be a more efficient way.

**Comment by Gpx** [comment]
I would add a test like this

```js
it('does not modify dates', function () {
  const date = new Date()
  const obj = { date }
  const converted = toSnakeCase(obj)
  expect(converted.date instanceof Date).to.be.true
})
```

**Comment by Moezalez** [comment]
@Gpx Isn't that already covered with [this](https://github.com/travelperk/case-converter/pull/10/files#diff-4fa5f7ba51fd0659874bda4afe103e80R88)?

Before is Date ^ After equals Before => After is date

**Comment by Gpx** [comment]
The PR looks good to me

**Pull request merged**
